# Generated by Django 4.1.3 on 2022-11-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teststripe', '0002_alter_typecurrency_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='teststripe.item')),
            ],
        ),
    ]
